# Define substitutions (optional but helps with versioning)
substitutions:
  _DEPLOYMENT_NAME: 'hello-world'
  _IMAGE: 'asia-south1-docker.pkg.dev/stage-443707/github-repository/git-imagee:v-1.1'

# Specify the logs bucket to store build logs
logsBucket: gs://cloud-build--pvt-logs

steps:
  # Step 1: Debug Step - List files in the current build context
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Listing files in the current build context:"
        ls -la
        echo "Deployment Name: ${_DEPLOYMENT_NAME}"
        echo "Image Name: ${_IMAGE}"

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']
  # args: ['build', '-t', 'asia-south1-docker.pkg.dev/stage-443707/github-repository/git-imagee:v-0.1', '.']

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']
  # args: ['push', 'asia-south1-docker.pkg.dev/stage-443707/github-repository/git-imagee:v-0.1']

# Step 4 only for first time deply:
  # Step 4: Apply the initial deployment if it doesn't exist
 - name: 'gcr.io/cloud-builders/kubectl'
   args:
     - 'apply'
     - '-f'
     - 'deployment.yaml'
   env:
     - 'CLOUDSDK_COMPUTE_REGION=asia-south1-a'
     - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'

  # Step 4: Deploy the application to GKE
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args:
  #     - 'set'
  #     - 'image'
  #     - 'deployment/${_DEPLOYMENT_NAME}'
  #     - '${_DEPLOYMENT_NAME}=${_IMAGE}'
  # ##    - 'deployment/hello-world'
  # ##    - 'hello-world=asia-south1-docker.pkg.dev/stage-443707/github-repository/git-imagee:v-0.1'
  #   env:
  #     - 'CLOUDSDK_COMPUTE_REGION=asia-south1-a'
  #     - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'

# Specify images to build
images:
  - '${_IMAGE}'  # Correct use of the substitution
  #- 'asia-south1-docker.pkg.dev/stage-443707/github-repository/git-imagee:v-0.1'

# Specify the worker pool configuration
options:
  pool:
    name: 'projects/stage-443707/locations/asia-south1/workerPools/cloud-build-private-pool'
