# Define substitutions (optional but helps with versioning)
substitutions:
  _SERVICE_NAME: 'hello-world'  # Cloud Run service name
  _IMAGE: 'asia-south1-docker.pkg.dev/stage-443707/github-repository/git-imagee:v-0.2'
  _REGION: 'asia-south1'  # Cloud Run deployment region

# Specify the logs bucket to store build logs
logsBucket: gs://cloud-build--pvt-logs

steps:
  # Step 1: Debug Step - List files in the current build context
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Listing files in the current build context:"
        ls -la
        echo "Service Name: ${_SERVICE_NAME}"
        echo "Image Name: ${_IMAGE}"

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  # Step 4: Deploy the application to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_IMAGE}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Allow public access; remove this for restricted access

# Specify images to build
images:
  - '${_IMAGE}'

# Specify the worker pool configuration
options:
  pool:
    name: 'projects/stage-443707/locations/asia-south1/workerPools/cloud-build-private-pool'
