# Deployment for Nginx pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment1
  labels:
    app: nginx-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container-2
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"         # Minimum 0.1 CPU core
            memory: "128Mi"     # Minimum 128 MB memory
          limits:
            cpu: "500m"         # Maximum 0.5 CPU core
            memory: "512Mi"     # Maximum 512 MB memory
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service1
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: nginx-pod
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.241 # Specify an internal IP from your VPC
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 # Match containerPort in the Deployment
  selector:
    app: nginx-pod # Match Deployment labels
  externalTrafficPolicy: Cluster
---
#For Deployment 1
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-app-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment1
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60   # Target 60% CPU usage
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70   # Target 70% memory usage
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-app-deployment
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nginx-pod
